"""data issues fixed

Revision ID: 5edf6a4187c4
Revises: 79e369bbb94e
Create Date: 2025-04-19 11:39:30.382865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edf6a4187c4'
down_revision: Union[str, None] = '79e369bbb94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute('ALTER TABLE candidates ALTER COLUMN need_sponsorship TYPE BOOLEAN USING need_sponsorship::BOOLEAN')
    op.execute('ALTER TABLE candidates ALTER COLUMN veteran TYPE BOOLEAN USING veteran::BOOLEAN ')
    op.execute('ALTER TABLE candidates ALTER COLUMN disability TYPE BOOLEAN USING disability::BOOLEAN')
    op.alter_column('candidates', 'need_sponsorship',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('candidates', 'veteran',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('candidates', 'disability',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'disability',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'veteran',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'need_sponsorship',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('candidates', 'skills',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
