""" final table

Revision ID: 6b8a4c7efd10
Revises: d764b71412c2
Create Date: 2025-04-17 10:32:28.390309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8a4c7efd10'
down_revision: Union[str, None] = 'd764b71412c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('race', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('candidates', 'cgpa',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'cgpa',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False)
    op.drop_column('candidates', 'gender')
    op.drop_column('candidates', 'race')
    # ### end Alembic commands ###
