"""Final candidate table 1

Revision ID: 79e369bbb94e
Revises: 05bbfba30943
Create Date: 2025-04-18 14:31:59.378973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e369bbb94e'
down_revision: Union[str, None] = '05bbfba30943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'major',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'school',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'major',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
