"""candidate table created

Revision ID: 85398c1b6ca4
Revises: 86adb9855838
Create Date: 2025-03-17 17:55:27.329007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85398c1b6ca4'
down_revision: Union[str, None] = '86adb9855838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('MiddleName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('FullName', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=14), nullable=False),
    sa.Column('DateOfBirth', sa.String(), nullable=False),
    sa.Column('Degree', sa.String(), nullable=False),
    sa.Column('Major', sa.String(), nullable=False),
    sa.Column('School', sa.String(), nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('CGPA', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('Skills', sa.String(), nullable=False),
    sa.Column('CompanyName', sa.String(), nullable=False),
    sa.Column('JobName', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('JobTittles', sa.String(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_candidates_Id'), 'candidates', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_Id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
