"""making id as user_id to identify the row in a table

Revision ID: 8c12ee01aa0e
Revises: ba1fb1e1823f
Create Date: 2025-03-24 11:12:13.841757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c12ee01aa0e'
down_revision: Union[str, None] = 'ba1fb1e1823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_id', table_name='candidates')
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.drop_column('candidates', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.create_index('ix_candidates_id', 'candidates', ['id'], unique=False)
    # ### end Alembic commands ###
