"""Changing candidate table from upper to lower letter columns

Revision ID: ba1fb1e1823f
Revises: 85398c1b6ca4
Create Date: 2025-03-18 13:57:26.308464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1fb1e1823f'
down_revision: Union[str, None] = '85398c1b6ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('candidates', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('middle_name', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('email', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('phone_number', sa.String(length=14), nullable=False))
    op.add_column('candidates', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('candidates', sa.Column('degree', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('major', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('school', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('candidates', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('candidates', sa.Column('cgpa', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('candidates', sa.Column('skills', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('company_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('job_name', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('description', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('job_titles', sa.String(), nullable=False))
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_candidates_Id', table_name='candidates')
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.drop_constraint('candidates_UserId_fkey', 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.drop_column('candidates', 'Email')
    op.drop_column('candidates', 'Major')
    op.drop_column('candidates', 'DateOfBirth')
    op.drop_column('candidates', 'UserId')
    op.drop_column('candidates', 'Degree')
    op.drop_column('candidates', 'Skills')
    op.drop_column('candidates', 'JobTittles')
    op.drop_column('candidates', 'CGPA')
    op.drop_column('candidates', 'Description')
    op.drop_column('candidates', 'CompanyName')
    op.drop_column('candidates', 'EndDate')
    op.drop_column('candidates', 'JobName')
    op.drop_column('candidates', 'PhoneNumber')
    op.drop_column('candidates', 'StartDate')
    op.drop_column('candidates', 'Id')
    op.drop_column('candidates', 'FirstName')
    op.drop_column('candidates', 'LastName')
    op.drop_column('candidates', 'FullName')
    op.drop_column('candidates', 'School')
    op.drop_column('candidates', 'MiddleName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('MiddleName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidates', sa.Column('School', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('FullName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('candidates', sa.Column('StartDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('PhoneNumber', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('JobName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('EndDate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('CompanyName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('CGPA', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('JobTittles', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Skills', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Degree', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('UserId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('DateOfBirth', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Major', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('Email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key('candidates_UserId_fkey', 'candidates', 'users', ['UserId'], ['id'])
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.create_index('ix_candidates_Id', 'candidates', ['Id'], unique=False)
    op.drop_column('candidates', 'user_id')
    op.drop_column('candidates', 'job_titles')
    op.drop_column('candidates', 'description')
    op.drop_column('candidates', 'job_name')
    op.drop_column('candidates', 'company_name')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'cgpa')
    op.drop_column('candidates', 'end_date')
    op.drop_column('candidates', 'start_date')
    op.drop_column('candidates', 'school')
    op.drop_column('candidates', 'major')
    op.drop_column('candidates', 'degree')
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'phone_number')
    op.drop_column('candidates', 'email')
    op.drop_column('candidates', 'full_name')
    op.drop_column('candidates', 'last_name')
    op.drop_column('candidates', 'middle_name')
    op.drop_column('candidates', 'first_name')
    op.drop_column('candidates', 'id')
    # ### end Alembic commands ###
