"""Email confirmation columns

Revision ID: cc0d67037df6
Revises: 4a37d6532c56
Create Date: 2025-03-07 20:19:09.107494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0d67037df6'
down_revision: Union[str, None] = '4a37d6532c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_token_expiration', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('confirm_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('confirm_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_confirmed')
    op.drop_column('users', 'confirm_token_expires')
    op.drop_column('users', 'cofirm_token')
    op.drop_column('users', 'email_token_expiration')
    op.drop_column('users', 'email_token')
    # ### end Alembic commands ###
