"""Finally all columns are added

Revision ID: d0b0a4dcbe90
Revises: 8c12ee01aa0e
Create Date: 2025-04-16 21:38:25.256315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b0a4dcbe90'
down_revision: Union[str, None] = '8c12ee01aa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('residence_address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('residence_city', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('residence_state', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('residence_zip_code', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('residence_country', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('school_start_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('school_end_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('currently_studying', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('school_address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('school_city', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('school_state', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('school_zip_code', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('school_country', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_start_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('job_end_date', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('currently_working', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('job_address', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_city', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_state', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_zip_code', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('job_country', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('github', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('portfolio', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('resume', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('need_sponsorship', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('veteran', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('disability', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('locations', sa.String(), nullable=True))
    op.alter_column('candidates', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'job_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'job_titles',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('candidates', 'start_date')
    op.drop_column('candidates', 'end_date')
    op.drop_column('candidates', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('candidates', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('candidates', 'job_titles',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'job_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('candidates', 'locations')
    op.drop_column('candidates', 'disability')
    op.drop_column('candidates', 'veteran')
    op.drop_column('candidates', 'need_sponsorship')
    op.drop_column('candidates', 'resume')
    op.drop_column('candidates', 'portfolio')
    op.drop_column('candidates', 'github')
    op.drop_column('candidates', 'linkedin')
    op.drop_column('candidates', 'job_country')
    op.drop_column('candidates', 'job_zip_code')
    op.drop_column('candidates', 'job_state')
    op.drop_column('candidates', 'job_city')
    op.drop_column('candidates', 'job_address')
    op.drop_column('candidates', 'currently_working')
    op.drop_column('candidates', 'job_end_date')
    op.drop_column('candidates', 'job_start_date')
    op.drop_column('candidates', 'school_country')
    op.drop_column('candidates', 'school_zip_code')
    op.drop_column('candidates', 'school_state')
    op.drop_column('candidates', 'school_city')
    op.drop_column('candidates', 'school_address')
    op.drop_column('candidates', 'currently_studying')
    op.drop_column('candidates', 'school_end_date')
    op.drop_column('candidates', 'school_start_date')
    op.drop_column('candidates', 'residence_country')
    op.drop_column('candidates', 'residence_zip_code')
    op.drop_column('candidates', 'residence_state')
    op.drop_column('candidates', 'residence_city')
    op.drop_column('candidates', 'residence_address')
    # ### end Alembic commands ###
