"""race, gender columns are added

Revision ID: d764b71412c2
Revises: d0b0a4dcbe90
Create Date: 2025-04-17 10:04:52.366773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd764b71412c2'
down_revision: Union[str, None] = 'd0b0a4dcbe90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('race', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('candidates', 'school_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'school_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'school_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'school_zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'school_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'linkedin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidates', 'resume',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'resume',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'linkedin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school_zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('candidates', 'school_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('candidates', 'gender')
    op.drop_column('candidates', 'race')
    # ### end Alembic commands ###
